version: '3.3'
services:
 db:
  build: ./banco
  image: etarefas/banco
  container_name: banco
  ports: 
    - "5433:5432"
 web:
  build: .
  depends_on: 
   - db
  image: etarefas/app
  container_name: app
  ports: 
    - "8080:8080" 
  external_links: 
    - db    
  restart: on-failure